apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  labels:
    project: roboshop
    component: shipping
    tier: backend
    env: dev
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: backend
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: shipping
      tier: backend
      env: dev
  template:
    metadata:
      labels:
        project: roboshop
        component: shipping
        tier: backend
        env: dev
    spec:
      containers:
      - name: shipping
        image: shanmukhatadisetti/shipping:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping
        ports:
        - name: shipping
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 1
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 1
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: backend
    env: dev
spec:
  selector:
    project: roboshop
    component: shipping
    tier: backend
    env: dev
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
